# NumPy & Series 문제

In [ ]:
# 문제 1. 
- 답지를 확인하고 알맞게 슬라이싱을 진행하세요. 

In [8]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])

In [ ]:
# 답지
[2, 4]

In [29]:
#답지
print(arr[1:5:2])  # 2번째 요소부터 5번째 요소까지, 2씩 건너뜀: [2, 4]

[[4 5 6]]


In [ ]:
# 문제 2. 다차원 배열에서 슬라이싱

In [17]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
# 답지
# [[2, 3], [5, 6]]

In [30]:
# 답지
# [[2, 3], [5, 6]]
arr[0:2, 1:3]  # 첫 번째와 두 번째 행, 두 번째와 세 번째 열 선택: 

array([[2, 3],
       [5, 6]])

In [ ]:
# 문제 3. 배열에서 슬라이싱과 조건 사용

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [31]:
# 답지
# [4, 5, 6]
arr[arr > 3]  

array([4, 5, 6, 7, 8, 9])

In [28]:
arr[3:6]

array([], shape=(0, 3), dtype=int64)

In [ ]:
# 문제 4. 배열의 일부 값 변경
- 두 번째와 세 번째 값을 10과 20으로 변경: [1, 10, 20, 4, 5]

In [33]:
arr = np.array([1, 2, 3, 4, 5])

In [ ]:
# 답지
array([ 1, 10, 20,  4,  5])

In [34]:
# 답지
arr[1:3] = [10, 20]  # 두 번째와 세 번째 값을 10과 20으로 변경: [1, 10, 20, 4, 5]
arr

array([ 1, 10, 20,  4,  5])

In [ ]:
# 문제 5. 다차원 배열의 축 기준으로 슬라이싱
- 모든 행의 두번째 열 선택

In [35]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
# 답지
# [2, 5, 8]

In [36]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 답지
arr[:, 1]  # 모든 행의 두 번째 열 선택: [2, 5, 8]

array([2, 5, 8])

In [ ]:
# 문제 6. 복합 조건(여러 조건)을 사용
- 2보다 크고 5보다 작은 값 조회

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
filtered_arr = arr[(arr > 2) & (arr < 5)]

In [ ]:
# 2보다 크고 5보다 작은 값

# 답지
[3, 4]

In [37]:
arr = np.array([1, 2, 3, 4, 5])
filtered_arr = arr[(arr > 2) & (arr < 5)]  # 2보다 크고 5보다 작은 값: [3, 4]

# 답지
[3, 4]

[3, 4]

In [ ]:
# 문제 7. 다차원 배열에 조건 적용
- 4보다 큰 값은 그대로, 나머지는 0으로 대체

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = np.where(arr > 4, arr, 0) 

In [ ]:
# 답지
[[0, 0, 0], [0, 5, 6], [7, 8, 9]]

In [38]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = np.where(arr > 4, arr, 0) 

# 답지
[[0, 0, 0], [0, 5, 6], [7, 8, 9]]

[[0, 0, 0], [0, 5, 6], [7, 8, 9]]

In [42]:
# 문제 8. series에 numpy 적용1
- 주어진 Series에서 값이 50보다 큰 경우에는 1로, 그렇지 않은 경우에는 0으로 변경하시오.
- numpy 메서드 이용 (numpy.where)

SyntaxError: invalid syntax (3020348358.py, line 2)

In [2]:
import pandas as pd
import numpy as np

# Pandas Series 생성
series = pd.Series([10, 55, 30, 70, 45])

In [ ]:
# 답지
# 결과 출력
# [0 1 0 1 0] <class 'numpy.ndarray'>

In [3]:
# 답지
# np.where를 사용하여 조건 적용
result = np.where(series > 50, 1, 0)

# 결과 출력
print(result)

[0 1 0 1 0]


In [ ]:
# 문제 9. series에 numpy 적용2
- 주어진 Series에서 값이 30보다 크고 60보다 작은 경우에는 해당 값에 10을 더하고, 그 외의 값은 그대로 두시오.
- numpy 메서드 이용 (numpy.where)

In [4]:
# Pandas Series 생성
series = pd.Series([25, 35, 45, 60, 75])

In [6]:
# Series 결과 답안
result_series = pd.Series([25, 45, 55, 60, 75])

# 결과 출력
print(result_series)

0    25
1    45
2    55
3    60
4    75
dtype: int64

SyntaxError: invalid syntax (4124837935.py, line 7)

In [7]:
# np.where를 사용하여 조건 적용
result = pd.Series(np.where((series > 30) & (series < 60), series + 10, series))

# 결과 출력
print(result)

0    25
1    45
2    55
3    60
4    75
dtype: int64


In [ ]:
# 문제 10. 다중 조건
- 주어진 Series에서 cond 리스트에 조건을 정의하고, 각 조건을 만족하는 값에 대해 다른 연산을 수행하여 새로운 Series를 생성하시오.
    + cond[0]: 값이 50보다 크면 해당 값을 2배로 증가시킴.
    + cond[1]: 값이 30보다 작으면 해당 값을 10으로 변경.
    + 그 외의 값은 그대로 유지.

In [8]:
series = pd.Series([25, 45, 55, 60, 75])

In [9]:
# 결과 답안
pd.Series([10, 45, 110, 120, 150])

0     10
1     45
2    110
3    120
4    150
dtype: int64

SyntaxError: invalid syntax (3232235158.py, line 4)

In [10]:
import pandas as pd
import numpy as np

# Pandas Series 생성
series = pd.Series([25, 45, 55, 60, 75])

# 조건 리스트 생성
cond = [
    series > 50,  # cond[0]: 값이 50보다 큰 경우
    series < 30   # cond[1]: 값이 30보다 작은 경우
]

# np.where를 사용하여 조건에 따른 연산 적용
result = pd.Series(
    np.where(cond[0], series * 2, 
             np.where(cond[1], 10, series))
)

# 결과 출력
print(result)

0     10
1     45
2    110
3    120
4    150
dtype: int64


In [52]:
##데이터프레임 생성

In [1]:
import numpy as np
import pandas as pd

In [11]:
2.1.1
2.2.3

- 첫번째 방법: 리스트 활용
- 두번째 방법: 딕셔너리 활용(강사 선호)

SyntaxError: invalid syntax (2635121292.py, line 1)

In [14]:
data = [
    ["039900", "알파코", 1000000, 10.05],
    ["039910", "A", 50000, 1.05],
    ["039900", "B", 1000, 1.28]
]

columns = ["종목코드", "종목명", "현재가", "등락률"]
df = pd.DataFrame(data=data, columns = columns)
df

종목코드  종목명      현재가    등락률
0  039900  알파코  1000000  10.05
1  039910    A    50000   1.05
2  039900    B     1000   1.28

In [15]:
data2 = {
    "종목코드" : ["039900", "039910", "039900"],
    "종목명": ["알파코", "A", "B"]
}

df2 = pd.DataFrame(data=data2)
df2

종목코드  종목명
0  039900  알파코
1  039910    A
2  039900    B

In [16]:
df.현재가

0    1000000
1      50000
2       1000
Name: 현재가, dtype: int64

In [17]:
df['현재가']

0    1000000
1      50000
2       1000
Name: 현재가, dtype: int64

In [18]:
df[['현재가']]

현재가
0  1000000
1    50000
2     1000

In [ ]:
##로우 인덱싱
- loc, iloc
    + loc : Label를 기준으로 인덱싱
    + iloc : index를 기준으로 인덱싱

In [24]:
import seaborn as sns

sns.__version__

'0.13.2'

In [25]:
iris = sns.load_dataset("iris")
iris

URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)>

In [27]:
#구글 코렙으로 실행
- https://colab.research.google.com/drive/1DRtRk9tv9LJCJKvErth_rlh2hL_In9Rl#scrollTo=NF4s1R-1X3Al